services:
  ruby:
    image: ruby
    working_dir: /app
    volumes:
      - .:/app
  python:
    image: python
    working_dir: /app
    volumes:
      - .:/app
  stk:
    image: stklos/stklos:2.00
    working_dir: /app
    volumes:
      - .:/app

